import { Signal, Zone, Stats } from '../types';

export const INITIAL_SIGNALS: Signal[] = [
  {
    id: 's1',
    title: 'Connectivity Outage: North Dorms',
    category: 'IT Infrastructure',
    location: 'North Dorms - Block A',
    timestamp: '12m ago',
    riskLevel: 'Critical',
    description: 'Structural Infrastructure • 8 nodes affected. Students reporting total loss of connectivity.',
    status: 'Open',
  },
  {
    id: 's2',
    title: 'Chemical Storage Variance',
    category: 'Safety',
    location: 'Science Dept',
    timestamp: '45m ago',
    riskLevel: 'Moderate',
    description: 'Pressure sensor deviation in Lab 4. Maintenance team notified.',
    status: 'Investigating',
  },
  {
    id: 's3',
    title: 'New SAP Intervention Request',
    category: 'Administration',
    location: 'Student Services',
    timestamp: '2h ago',
    riskLevel: 'Low',
    description: 'Academic Distress Signal triggered by attendance logs.',
    status: 'Open',
  },
];

// SVKM Vile Parle Colleges
export const ZONES: Zone[] = [
  {
    id: 'z1',
    name: 'SVKM’s NMIMS',
    category: 'Safety',
    riskLevel: 'Critical',
    signalCount: 12,
    coordinates: { x: 50, y: 50 },
    latLng: [19.1034, 72.8369],
    details: 'Zone A • Critical Priority',
  },
  {
    id: 'z2',
    name: 'Narsee Monjee College',
    category: 'Facilities',
    riskLevel: 'Moderate',
    signalCount: 3,
    coordinates: { x: 52, y: 48 },
    latLng: [19.1028, 72.8365],
    details: 'Zone B • HVAC Maintenance',
  },
  {
    id: 'z3',
    name: 'Mithibai College',
    category: 'Safety',
    riskLevel: 'Stable',
    signalCount: 0,
    coordinates: { x: 48, y: 52 },
    latLng: [19.1025, 72.8360],
    details: 'Zone C • All Clear',
  },
  {
    id: 'z4',
    name: 'D. J. Sanghvi Engineering',
    category: 'IT',
    riskLevel: 'Critical',
    signalCount: 8,
    coordinates: { x: 55, y: 45 },
    latLng: [19.1070, 72.8360],
    details: 'Zone D • Server Overheat',
  },
  {
    id: 'z5',
    name: 'Usha Pravin Gandhi College',
    category: 'General',
    riskLevel: 'Stable',
    signalCount: 0,
    coordinates: { x: 51, y: 51 },
    latLng: [19.1029, 72.8372],
    details: 'Zone E • Monitoring',
  },
  {
    id: 'z6',
    name: 'Dr. Bhanuben Nanavati Pharmacy',
    category: 'Safety',
    riskLevel: 'Low',
    signalCount: 1,
    coordinates: { x: 53, y: 49 },
    latLng: [19.1022, 72.8358],
    details: 'Zone F • Lab Safety Check',
  },
  {
    id: 'z7',
    name: 'Jitendra Chauhan Law College',
    category: 'Facilities',
    riskLevel: 'Stable',
    signalCount: 0,
    coordinates: { x: 50, y: 53 },
    latLng: [19.1026, 72.8362], // Co-located typically, slightly offset for map
    details: 'Zone G',
  },
  {
    id: 'z8',
    name: 'Pravin Gandhi College of Law',
    category: 'IT',
    riskLevel: 'Moderate',
    signalCount: 2,
    coordinates: { x: 49, y: 50 },
    latLng: [19.1030, 72.8375],
    details: 'Zone H • Network Slowdown',
  },
  {
    id: 'z9',
    name: 'Bhagubhai Mafatlal Polytechnic',
    category: 'Facilities',
    riskLevel: 'Critical',
    signalCount: 5,
    coordinates: { x: 45, y: 55 },
    latLng: [19.1045, 72.8355],
    details: 'Zone I • Power Fluctuation',
  },
  {
    id: 'z10',
    name: 'Acharya A. V. Patel Jr College',
    category: 'General',
    riskLevel: 'Stable',
    signalCount: 0,
    coordinates: { x: 47, y: 53 },
    latLng: [19.1038, 72.8368],
    details: 'Zone J',
  },
  {
    id: 'z11',
    name: 'J. V. Parekh Int. School',
    category: 'Safety',
    riskLevel: 'Low',
    signalCount: 1,
    coordinates: { x: 54, y: 46 },
    latLng: [19.1055, 72.8345],
    details: 'Zone K • Playground monitor',
  },
  {
    id: 'z12',
    name: 'C. N. M. School',
    category: 'General',
    riskLevel: 'Stable',
    signalCount: 0,
    coordinates: { x: 55, y: 47 },
    latLng: [19.1060, 72.8348],
    details: 'Zone L',
  },
  {
    id: 'z13',
    name: 'Smt. Gokalibai High School',
    category: 'General',
    riskLevel: 'Stable',
    signalCount: 0,
    coordinates: { x: 46, y: 50 },
    latLng: [19.1015, 72.8380],
    details: 'Zone M',
  },
  {
    id: 'z14',
    name: 'C. B. Patel Research Centre',
    category: 'Safety',
    riskLevel: 'Moderate',
    signalCount: 4,
    coordinates: { x: 48, y: 48 },
    latLng: [19.1020, 72.8350],
    details: 'Zone N • Chemical Alert',
  }
];

export const INITIAL_STATS: Stats = {
  healthScore: 92,
  activeSignals: 14,
  trend: [65, 70, 68, 75, 80, 85, 92],
};

export const NOTIFICATIONS = [
  { id: 1, title: 'High Risk at DJ Sanghvi', time: '2m ago', read: false },
  { id: 2, title: 'Network Restore: Library', time: '15m ago', read: false },
  { id: 3, title: 'Shift Change Report Ready', time: '1h ago', read: true },
  { id: 4, title: 'Maintenance Scheduled: Zone B', time: '3h ago', read: true },
];